### ISSUE TITLE
In Character Creation, clicking in filter text box is treated as a form submission

### ISSUE THREAD

**Issue by wastevens** [gnu-lorien/twistedvines#20]
For example, create a new character, proceed to character creation.

Pick your clan.  Click in the filter- your 'empty' clan is submitted.

You can scroll down to the clan you want.

(See for both Clan and Archtype selection; I'm presently assuming it's generalized)

**Comment by gnu-lorien** [comment]
Yep. There are essentially two types of data associated with characters right now: traits and texts. Traits are a SimpleTrait object with value, name, and category. Texts are things like Clan and Faction. Both of those sections use the same UI to pick texts. I must've handled the listener incorrectly on that page and never actually *used* the filter because the choice list is so small.
